name: Laravel 8
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: php:8.0-cli
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: PHPUnit
        run: |
          apt update
          apt install -y libzip-dev unzip
          pecl install xdebug
          docker-php-ext-enable xdebug
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          composer require orchestra/testbench:^v6 --dev
          XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-clover coverage.xml --coverage-filter src/ tests/
      - name: codecov
        uses: codecov/codecov-action@v1
        with:
          name: laravel-8
      - name: Create Laravel project
        run: |
          composer create-project --prefer-dist laravel/laravel laravel-demo "8.*"
          cd laravel-demo && composer require --dev laravel-fans/docker:dev-main && php artisan docker:publish
  push-demo:
    name: Push Demo Code
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./laravel-demo
          publish_branch: laravel-8
