name: Laravel 8
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: php:8.0-cli
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: PHPUnit
        run: |
          apt update
          apt install -y libzip-dev unzip
          pecl install xdebug
          docker-php-ext-enable xdebug
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          composer require orchestra/testbench:^v6 --dev
          XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-clover coverage.xml --coverage-filter src/ tests/
      - name: codecov
        uses: codecov/codecov-action@v1
        with:
          name: laravel-8
  push-demo:
    name: Push Demo Code
    needs: test
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    container:
      image: php:8.0-cli
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Create laravel project
        run: |
          apt update
          apt install -y libzip-dev unzip
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          git checkout --orphan laravel-8
          composer create-project --prefer-dist laravel/laravel laravel-demo "8.*"
          mv laravel-demo/* laravel-demo/.* .
          composer require --dev laravel-fans/docker:dev-main
          php artisan docker:publish
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "feat: laravel 8"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: laravel-8
          force: true
